"""add shelves

Revision ID: 56be88ea4c10
Revises: de85be3fd0c4
Create Date: 2026-07-05 20:35:17.058309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56be88ea4c10'
down_revision = 'de85be3fd0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_shelf_name')
    )
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelves_user_id'), ['user_id'], unique=False)

    op.create_table('shelf_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'book_id', name='uq_shelf_book')
    )
    with op.batch_alter_table('shelf_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_books_shelf_id'), ['shelf_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelf_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelf_books_shelf_id'))

    op.drop_table('shelf_books')
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelves_user_id'))

    op.drop_table('shelves')
    # ### end Alembic commands ###
